// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlertsBucket: typeof import('./src/components/organisms/AlertsBucket.vue')['default']
    AvatarProfileChip: typeof import('./src/components/molecules/AvatarProfileChip.vue')['default']
    BaseTemplate: typeof import('./src/components/templates/BaseTemplate.vue')['default']
    ButtonComponent: typeof import('./src/components/atoms/ButtonComponent.vue')['default']
    ButtonElement: typeof import('./src/components/atoms/ButtonElement.vue')['default']
    CardResumeProfile: typeof import('./src/components/molecules/CardResumeProfile.vue')['default']
    ChartDepthBar: typeof import('./src/components/molecules/ChartDepthBar.vue')['default']
    ChartDepthPie: typeof import('./src/components/molecules/ChartDepthPie.vue')['default']
    ChartDepthTimeLines: typeof import('./src/components/molecules/ChartDepthTimeLines.vue')['default']
    ChartGasPie: typeof import('./src/components/molecules/ChartGasPie.vue')['default']
    ChartThemePie: typeof import('./src/components/molecules/ChartThemePie.vue')['default']
    CreditsImages: typeof import('./src/components/atoms/CreditsImages.vue')['default']
    DiveFormView: typeof import('./src/components/views/DiveFormView.vue')['default']
    DiveLogView: typeof import('./src/components/views/DiveLogView.vue')['default']
    FooterBar: typeof import('./src/components/molecules/FooterBar.vue')['default']
    FormControlComboBox: typeof import('./src/components/molecules/FormControlComboBox.vue')['default']
    FormControlDate: typeof import('./src/components/molecules/FormControlDate.vue')['default']
    FormControlDoubleText: typeof import('./src/components/molecules/FormControlDoubleText.vue')['default']
    FormControlGasGroup: typeof import('./src/components/molecules/FormControlGasGroup.vue')['default']
    FormControlGasPanel: typeof import('./src/components/molecules/FormControlGasPanel.vue')['default']
    FormControlNumber: typeof import('./src/components/molecules/FormControlNumber.vue')['default']
    FormControlRadioList: typeof import('./src/components/molecules/FormControlRadioList.vue')['default']
    FormControlSelect: typeof import('./src/components/molecules/FormControlSelect.vue')['default']
    FormControlText: typeof import('./src/components/molecules/FormControlText.vue')['default']
    FormDiveCreate: typeof import('./src/components/organisms/FormDiveCreate.vue')['default']
    FormSettingsDelete: typeof import('./src/components/organisms/FormSettingsDelete.vue')['default']
    FormSettingsEdit: typeof import('./src/components/organisms/FormSettingsEdit.vue')['default']
    FormUserModal: typeof import('./src/components/organisms/FormUserModal.vue')['default']
    HeaderBar: typeof import('./src/components/organisms/HeaderBar.vue')['default']
    HomeParallax: typeof import('./src/components/molecules/HomeParallax.vue')['default']
    HomeView: typeof import('./src/components/views/HomeView.vue')['default']
    LogoType: typeof import('./src/components/atoms/LogoType.vue')['default']
    MenuBurger: typeof import('./src/components/organisms/MenuBurger.vue')['default']
    MenuDrawer: typeof import('./src/components/organisms/MenuDrawer.vue')['default']
    ProfileView: typeof import('./src/components/views/ProfileView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsView: typeof import('./src/components/views/SettingsView.vue')['default']
    StrateDepthCharts: typeof import('./src/components/organisms/StrateDepthCharts.vue')['default']
    StrateGasCharts: typeof import('./src/components/organisms/StrateGasCharts.vue')['default']
    StrateThemesCharts: typeof import('./src/components/organisms/StrateThemesCharts.vue')['default']
  }
}
