// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlertsBucket: typeof import('./src/components/organisms/AlertsBucket.vue')['default']
    BaseTemplate: typeof import('./src/components/templates/BaseTemplate.vue')['default']
    ButtonComponent: typeof import('./src/components/atoms/ButtonComponent.vue')['default']
    CardErrorData: typeof import('./src/components/molecules/CardErrorData.vue')['default']
    CardTemplate: typeof import('./src/components/templates/CardTemplate.vue')['default']
    ChartBar: typeof import('./src/components/molecules/ChartBar.vue')['default']
    ChartCalendar: typeof import('./src/components/molecules/ChartCalendar.vue')['default']
    ChartDoughnut: typeof import('./src/components/molecules/ChartDoughnut.vue')['default']
    ChartLine: typeof import('./src/components/molecules/ChartLine.vue')['default']
    ChartPie: typeof import('./src/components/molecules/ChartPie.vue')['default']
    ChartProgress: typeof import('./src/components/molecules/ChartProgress.vue')['default']
    CreditsImages: typeof import('./src/components/atoms/CreditsImages.vue')['default']
    DiveFormView: typeof import('./src/components/views/DiveFormView.vue')['default']
    DivesList: typeof import('./src/components/organisms/DivesList.vue')['default']
    DivesListView: typeof import('./src/components/views/DivesListView.vue')['default']
    FooterBar: typeof import('./src/components/molecules/FooterBar.vue')['default']
    FormControlComboBox: typeof import('./src/components/molecules/FormControlComboBox.vue')['default']
    FormControlDate: typeof import('./src/components/molecules/FormControlDate.vue')['default']
    FormControlDoubleText: typeof import('./src/components/molecules/FormControlDoubleText.vue')['default']
    FormControlGasGroup: typeof import('./src/components/molecules/FormControlGasGroup.vue')['default']
    FormControlGasPanel: typeof import('./src/components/molecules/FormControlGasPanel.vue')['default']
    FormControlNumber: typeof import('./src/components/molecules/FormControlNumber.vue')['default']
    FormControlRadioList: typeof import('./src/components/molecules/FormControlRadioList.vue')['default']
    FormControlSelect: typeof import('./src/components/molecules/FormControlSelect.vue')['default']
    FormControlText: typeof import('./src/components/molecules/FormControlText.vue')['default']
    FormDiveCreate: typeof import('./src/components/organisms/FormDiveCreate.vue')['default']
    FormDiveDeleteModal: typeof import('./src/components/organisms/FormDiveDeleteModal.vue')['default']
    FormSettingsDelete: typeof import('./src/components/organisms/FormSettingsDelete.vue')['default']
    FormSettingsEdit: typeof import('./src/components/organisms/FormSettingsEdit.vue')['default']
    FormUserModal: typeof import('./src/components/organisms/FormUserModal.vue')['default']
    HeaderBar: typeof import('./src/components/organisms/HeaderBar.vue')['default']
    HomeView: typeof import('./src/components/views/HomeView.vue')['default']
    LogoType: typeof import('./src/components/atoms/LogoType.vue')['default']
    MenuDrawer: typeof import('./src/components/organisms/MenuDrawer.vue')['default']
    PanelTemplate: typeof import('./src/components/templates/PanelTemplate.vue')['default']
    ParallaxHeading: typeof import('./src/components/molecules/ParallaxHeading.vue')['default']
    ProfileView: typeof import('./src/components/views/ProfileView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsView: typeof import('./src/components/views/SettingsView.vue')['default']
    StrateCalendar: typeof import('./src/components/organisms/StrateCalendar.vue')['default']
    StrateDepthCharts: typeof import('./src/components/organisms/StrateDepthCharts.vue')['default']
    StrateGasCharts: typeof import('./src/components/organisms/StrateGasCharts.vue')['default']
    StrateTemplate: typeof import('./src/components/templates/StrateTemplate.vue')['default']
    StrateThemesCharts: typeof import('./src/components/organisms/StrateThemesCharts.vue')['default']
  }
}
