export enum ButtonActions {
  SUBMIT_LOGIN = "SUBMIT_LOGIN",
  SUBMIT_DIVE_CREATE = "SUBMIT_DIVE_CREATE",
  GOTO_LOGIN = "GOTO_LOGIN",
  GOTO_LOGOUT = "GOTO_LOGOUT",
  GOTO_REGISTER = "GOTO_REGISTER",
  GOTO_GITHUB = "GOTO_GITHUB",
}
