export enum GraphqlActions {
  DIVING_ROLES = "QUERY_DIVING_ROLES",
  DIVING_ENVIRONMENTS = "QUERY_DIVING_ENVIRONMENTS",
  DIVING_TYPES = "QUERY_DIVING_TYPES",
  FIRST_DIVE = "QUERY_FIRST_DIVE",
  LAST_DIVE = "QUERY_LAST_DIVE",
  GAS_BY_DIVES = "QUERY_GASTANKS_BY_DIVES",
  DIVES_BY_DATES = "QUERY_DIVES_BY_DATES",
  DEPTH_TIME_BY_DIVES = "QUERY_DEPTH_AND_TIME_BY_DIVES",
  CREATE_DIVE = "MUTATION_CREATE_DIVE",
}
