export enum GraphqlActions {
  DIVING_ROLES = "QUERY_DIVING_ROLES",
  DIVING_ENVIRONMENTS = "QUERY_DIVING_ENVIRONMENTS",
  DIVING_TYPES = "QUERY_DIVING_TYPES",
  GAS_BY_DIVES = "QUERY_GASTANKS_BY_DIVES",
  CREATE_DIVE = "MUTATION_CREATE_DIVE",
}
